[project]
name = "smiles_tools"
version = "0.1.1"

dependencies = [
    "numpy ~= 1.24.1",
    "pandas ~= 1.5.3",
    "rdkit ~= 2022.9.4"
]

[build-system]
requires = [
    "setuptools>=54",
    "wheel"
]
build-backend = "setuptools.build_meta"