[project]
name = "c_wrapper"
version = "0.1.0"
description = "Some helper functions written in C"

dependencies = [
    "numpy ~= 1.24.1",
]

[build-system]
requires = [
    "setuptools>=54",
    "wheel"
]
build-backend = "setuptools.build_meta"